---
models.app:
  ycappuccino_endpoints_service: true
  ycappuccino_service_comm_storage: true
layers:
  ycappuccino_endpoints_service:
    active: true

  ycappuccino_service_comm:
    active: true
    host: localhost
    port: 0
    scheme: http
  ycappuccino_service_comm_storage:
    active: true
name: endpoints_service
bundle_prefix: ycappuccino

